tasks:
  - init: npm install
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-typescript-next
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint